### PR TITLE
Fix for android advertisement polling

### PR DESCRIPTION
**Pull request by CatapultJesse**
https://github.com/innoveit/react-native-ble-manager/issues/376

### CODE REVIEW

**Comment by marcosinigaglia** [comment]
Hi, i'm not sure that the pull is correct, is it not better to change updateData(ScanRecord scanRecord) in Peripheral class?

**Comment by CatapultJesse** [comment]
It could well be. I'm not sure how the native code actually works, I just implemented the fix mentioned in the issue and tested it behaved as expected

**Comment by CatapultJesse** [comment]
Yeah there's something weird going on, its better than it was before in terms of actually getting the new data, but it's still not actually getting the new data every time.

**Comment by stevesuyao** [comment]
Adding `advertisingDataBytes = scanRecord.getBytes()` to `updateData(scanRecord scanRecord) `works.
https://github.com/innoveit/react-native-ble-manager/blob/3c877897d3e4156df7e54a0f7ba0d1e3c412b0a9/android/src/main/java/it/innove/Peripheral.java#L370-L372
should be 
```java
public void updateData(ScanRecord scanRecord) { 
 	advertisingData = scanRecord; 
        advertisingDataBytes = scanRecord.getBytes();
 } 
```

Just tested it on Android  7.0 with RN 0.57.6

Thanks @marcosinigaglia.

**Comment by marcosinigaglia** [comment]
Hi @stevesuyao , can you make another PR?

**Pull request closed without merging**
