### PR TITLE
Fix manufacturer data

### PR DESCRIPTION
**Pull request by mjamry**
This PR contains proposal of solution for #1099.

Unfortunately, i'm not familiar enough and do not have the right software/hardware to modify iOS part of this library.
So if these changes are fine for you, please fell free to add iOS part corresponding to this update.

Please be aware that this can be considered as breaking change, as one of the main interfaces is modified. But in my opinion it is required to change to sort things out.

### CODE REVIEW

**Comment by marcosinigaglia** [comment]
Hi @mjamry , thanks for your PR. Can you also add a `manufacturerRawData` field? So we can have the same field in the ios part.

**Comment by mjamry** [comment]
> Hi @mjamry , thanks for your PR. Can you also add a `manufacturerRawData` field? So we can have the same field in the ios part.

Are you talking about AdvertisingData interface ?

There is already a manufacturerData field, which is defined as a Record. Why there is another field needed in your opinion ? I don't see any reason, but maybe i'm missing something :) 

```
export interface AdvertisingData {
  isConnectable?: boolean;
  localName?: string;
  manufacturerData?: CustomAdvertisingData;
  rawData?: CustomAdvertisingData;
  manufacturerData?: Record<string, CustomAdvertisingData>;
  serviceData?: Record<string, CustomAdvertisingData>;
  serviceUUIDs?: string[];
  txPowerLevel?: number;
```

**Comment by marcosinigaglia** [comment]
Since I don't know if is easy to replicate your changes in the iOS side I prefer to have at least one common field for the manufacturer data. In the iOS side there is for sure the raw data of the manufacturer field so I'm asking to add also that in the Android side: `advertising.putMap("manufacturerRawData", byteArrayToWritableMap(advertisingDataBytes.getManufacturerSpecificData()));`

**Comment by mjamry** [comment]
Ok, I got your point.

What we NOW have as manufacturer data is in fact the whole advertise frame. After my changes, it will be moved to the advertiseDataRaw. We can stop at this point, and it will be valid and more intuitive for both Android and iOS.

What additionally was done is that i've used [Android's API](https://developer.android.com/reference/android/bluetooth/le/AdvertiseData#getManufacturerSpecificData())
Which helps with getting only specified part of whole frame and give already extracted company ID. I'm sure this will be achievable also on iOS as long as we have access to the whole advertise frame. What is needed is to parse the frame properly.

In my opinion, another field (manufacturerDataRaw) is an overkill and is not needed. BTW. all fields are marked as optional, so it shouldn't be a problem for consumers of AdvertisingData interface even if this will be empty.

PS. What you are pointing here 
`Android side: advertising.putMap("manufacturerRawData", byteArrayToWritableMap(advertisingDataBytes.getManufacturerSpecificData()));`

Is not so straight forward to achieve as Android is not returning raw data frame, but:
"Returns an array of manufacturer Id and the corresponding manufacturer specific data."

So it will require additional data transformation to put company ID back to the array to have real rawData. So i guess it would be better to use this effort on iOS and make our API (AdvertisingData interface) clean and readable.

Do you see my point here ? If you need more details about how advertise data frame if formatted and how to detect manufacturer data i'll be happy to help :)

**Pull request merged**
