### PR TITLE
chore/switch project to ts

### PR DESCRIPTION
**Pull request by matgardon**
chore (package.json) handle typescript project compilation & publishing:
- switch project targets & scripts to support typescript source code and both esm & cjs module outputs as documented in https://cmdcolin.github.io/posts/2021-12-31-npm-package and similar to what https://github.com/callstack/react-native-builder-bob is doing.

chore (android) fix android project dependencies:
- android project was not able to build standalone, this commits fixes that behavior.
- not sure about gradle-wrapper & gradlew files, they are supposed to be comited to be able to build the project, but they were not included in this lib until now: check with maintainer.
- please note: the current AndroidManifest has an outdated permission declaration scheme, as some are not required at all times (COARSE_LOCATION) and some are missing (SCAN, CONNECT, FINE_LOC for SDK 29-31) because the project code requires them (checking on permissions to connect & scan). But adding them may trigger side effects when manifest merging happens in client apps, so I preferred not including them. It may be a good idea to clean up outdated permissions in this lib manifest to avoid interfering with client apps.

feat (BleManger) rewrite to TS
- better type documentations on scan options
- all functions are typed directly into the BleManager file (index.ts), all external types including enums are in their own file (types.ts) and re-exported in index.ts.
- a few typing improvements to BleManager functions on promise return types, function documentations, default values etc.

=> usage documentation on bundling & publishing the lib is coming in next PR (refactor example project, fix android permissions & documentation), sorry for not splitting changes properly.

### CODE REVIEW

**Comment by marcosinigaglia** [comment]
Hi @matgardon , I never used TS before, so have i to build the lib before publish it?

**Comment by matgardon** [comment]
Hi @marcosinigaglia indeed there is a compile step involved, which should be taken care of (once you run `npm install` to fetch a local typescript compiler) byt the npm scripts defined in `package.json`:

```
 "preversion": "npm run build",
 "postversion": "git push --follow-tags"
 ```
 
 I've not tested it though so you should make sure you do have files in the `/dist` folder and those files are packaged into the published bundle. You can confirm the behavior because the package.json list as entry point the files published in the dist/ folder, so it better be there.
 
 The build job will also clean any previoulsy build dist files to make sure the output is always up to date at the time of publishing.
 
 Also, please take a look at my commit questions, specifically:
 
 - I've included the gradle wrapper & gradlew scripts inside the src, because I believe they are needed to compile the local project standalone, but you didn't include them so please confirm before accepting the PR.
 
 I'm available for any questions you may have with TS or changes to the publishing flow, also in the commits are referenced certain articles which might be helpfull:
 - https://cmdcolin.github.io/posts/2021-12-31-npm-package
 - https://github.com/callstack/react-native-builder-bob

**Comment by marcosinigaglia** [comment]
I don't think the gradle wrapper & gradlew scripts is needed, I didn't publish the compiled Android/iOS part.

**Comment by matgardon** [comment]
Hi @marcosinigaglia , you're right, I've synced the fork & removed the unnecessary gradle parts. These are useful only when building the lib standalone (if you want to make sure the project compiles correctly on its own) but they are not necessary when the lib is used by a client project.

I would argue that could still be useful to include them to make sure the lib compiles properly with a specific version of RN & associated gradle plugin, as it may "guarantee" compatibility with a RN & Android version, but that will probably be for later.

**Comment by matgardon** [comment]
@marcosinigaglia also, the last PR you merged changed the minSDK version on Android:

In Peripheral.java, when using `forEach` you need to target SDK 24+, instead of the current SDK 21+.

This change was probably not voluntary, but that's why I build the lib standalone in AndroidStudio, I get checks on stuff like this too. I'm not sure you want to deprecate SDKs 21 to 23, because that would make other stuff in your codebase redundant (checks on Build.VERSION.SDK_INT >= M for example).

RN is still on minSDK 21 for now.

I though you should now and see what you want to do with that.

**Comment by matgardon** [comment]
@marcosinigaglia I'm a little under pressure right now, and I think that would make sense to separate the PRs too considering this one is an important technical change although the code itself hasn't changed much.

**Comment by marcosinigaglia** [comment]
Ok @matgardon , if you think the PR is ready I'll  merge it.

**Comment by matgardon** [comment]
@marcosinigaglia I think it is ready to merge, but without publishing it for now, in order to check that everything is in place & working on master. I also have subsequent PRs waiting on my fork:

- fix example project, rewrite in TS etc (https://github.com/matgardon/react-native-ble-manager/tree/chore/upgrade-example-project)
- support batch scan results (https://github.com/matgardon/react-native-ble-manager/tree/feat/support-batch-scan-results-on-android)
- support filter by advertising name (https://github.com/matgardon/react-native-ble-manager/tree/feat/support-android-scan-filter-by-advertising-name)

I don't know how you want to proceed but maybe this seems like a good time to bump major ? so that everyone having potentially different configs than us can re-check everything is in line in their environment without anything broken at compile time etc.

I'm using my updated master with no problem using git packages (https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub) and it works that way, but we need to make sure the npm publish steps work fine (which only you can do I guess ?)

**Comment by marcosinigaglia** [comment]
Hi @matgardon , can you check if the last release it's ok?

**Comment by matgardon** [comment]
Hi @marcosinigaglia, the package seems to work but include too many files, because I used the package.json files prop, which seems to override the npmignore file. let me shoot a PR for that

**Pull request merged**
