### PR TITLE
Legacy Scan service filter

### PR DESCRIPTION
**Pull request by yuezaixz**
Legacy Scan service filter

### CODE REVIEW

**Comment by marcosinigaglia** [comment]
Hi, can you explain the purpose of the PR?

**Comment by yuezaixz** [comment]
Hi, it add filter in pre-lollipop devices.
According to advertisement data to filter in mLeScanCallback.

**Comment by yuezaixz** [comment]
sry, the PR had some problems. Some code is copied from the my old project ,  I think I can improve it and then submit a new PR.

**Comment by marcosinigaglia** [comment]
Ok, thank you.

**Pull request closed without merging**
