### PR TITLE
Android command queue

### PR DESCRIPTION
**Pull request by dbarth**
This patch serializes read/write/setNotify operations sent to the Android stack, by using a command queue.
This improves BLE reliability for Android apps to bring them on par with iOS. The serialization ensures that read and writes can be sent as fast as possible from the react layer without the OS panicking about overlapping operations.

The new code uses portions from the Blessed library: https://github.com/weliem/blessed-android/

### CODE REVIEW

**Comment by dbarth** [comment]
A quick note to say that the code is still in testing.
This PR is created early to gather feedback about the quite invasive code changes.

**Comment by marcosinigaglia** [comment]
Hi @dbarth , are you still testing?

**Comment by dbarth** [comment]
Hi @marcosinigaglia, still testing yes, but it's rather stable from the results i get from my devel branch.
This PR needs an update to build / work cleanly on the tip of master, cause i'm still on a pre-AndroidX RN.
I can propose an update this week-end.

**Comment by maartenvandillen** [comment]
Very interested in this. Let me know when this is merged so I can test it

**Comment by marcosinigaglia** [comment]
Hi @maartenvandillen , can you do some test?

**Comment by maartenvandillen** [comment]
Yes working great, thank you! My use case is a button with onPressIn and onPressOut both firing a write and I was missing a write on onPressOut when releasing too quickly. With the new Peripheral.java this is working now. Can you bump the version?

**Comment by dbarth** [comment]
FWIW, the use case here is to have command packets sent in a stream while receiving a stream of both JSON and binary at a very fast pace for image transfer. Without the send queue, collisions were happening almost immediately. This brings the Android side on par with iOS in that respect.

**Comment by maartenvandillen** [comment]
Awesome. Thanks for implementing this!

**Comment by anwarhamr** [comment]
@dbarth commit e8fb1e1 breaks buffering messages from notifications.  Is there a reason you did not include this in your refactor?  This has broken our product.

**Comment by dbarth** [comment]
@anwarhamr not really, sorry, I tried preserving the logic but I'm not using this feature: where does it break?

**Comment by anwarhamr** [comment]
You removed cache of all items received. the logic to make it work if straight forward.  Buffer n items then send when buffer is full. this was added limit using the bridge frequently for data that comes in bursts.  I started to try and implement the change back over top of what you've done but what you've done is a lot more complicated than what was there. And I didn't want to break your stuff. perhaps we can work together or I can answer questions.

**Comment by lijutsang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by anwarhamr** [comment]
@dbarth yep.   Version 7.5 has the code working.  I'll look into adding some tests; I didn't do so initially because I didn't have a clue as to where to start.  I'm not a java programmer so adding even more code/files was intimidating.   
This feature is only supported on Android.  
Most of the work is done in Peripheral in .setNotify and .onCharacteristicChanged where a buffer is created and added until it's full.  The serialization that you added I'm not sure about but I'm guessing that if you add the buffer to your serialization calls it may just work if you add back in my logic using the buffer.

**Pull request merged**
