### PR TITLE
Allowing multiple concurrent promises, to fix #949

### LINKED ISSUE #949: If connect() called multiple times on same peripheralID, only the last promise will resolve.
**Describe the bug**
In my app, there are multiple triggers for the app to try to connect to a device, and sometimes these overlap. In such a case, the connect() function would be called multiple times. However, only one of those function calls would resolve. The remainder would hang forever.

I glanced at the Android code, inside the `Peripheral.java` file, and it looks like this is being caused by the `connectCallback` variable being overwritten with the callback from the most recent call. This could be fixed by changing `connectCallback` into a list of callbacks, so that multiple could be used.

I'm less skilled at reading the iOS code, but it looks like it uses a similar approach with the connectCallbacks dictionary, since each entry in that dictionary stores just a single callback for the associated device ID.

(It looks like the same approach is used for various other functions. Ideally, they would all be updated so that they can handle multiple requests)

**To Reproduce**
```
const connect = (label: string) => {
	BleManager.connect(macAddress)
		.then(() => console.log("Connected for:", label))
		.catch(() => console.log("Connection failed for:", label))
}
connect("first attempt") // This will never resolve
connect("second attempt") // This will either resolve or be rejected
```

When running this code, you will see either the .then or .catch fire for the second attempt, but not for the first attempt.

In the past, I've also seen this produce a 'no callback found' error, although it's fairly inconsistent, so I don't have the exact wording of that error.

**Expected behavior**
Each .connect() function promise should either resolve or reject. The same should be true for any other BLE manager functions which return promises.

**Smartphone (please complete the following information):**
 - Device: Oppo Reno Z
 - OS: Android v11
 - react-native-ble-manager version: 8.6.0
 - react-native version: 0.70.6

### PR DESCRIPTION
**Pull request by Joseph-Alley**
I previously created #949 to cover issues I was having where some promises would not resolve, because they were being overridden by a later promise.

I've since found the time to investigate further, and I've fixed up these issues. Now, each callback will instead be a list of callbacks. Whenever a callback would be assigned, it is instead added to the list. Whenever a callback would be invoked, instead the whole list is invoked.

I tested this on both Android and iOS, and everything worked for me. However, these aren't languages I program in very often, so let me know if there's anything I overlooked.

### CODE REVIEW

**Comment by marcosinigaglia** [comment]
Hi @Joseph-Alley looks ok, probably not the perfect solution but it can be fine.

**Comment by matgardon** [comment]
@marcosinigaglia this is the PR that breaks minSDK 21 compat, due too the use of `forEach` to go over list of callbacks.
It was indeed only introduced in java 8, as crazy as that sounds : https://stackoverflow.com/questions/42276329/unable-to-use-foreach-and-lambda-in-android-min-sdk-version-less-than-24.

**Comment by Joseph-Alley** [comment]
Ahh, my bad. Give me a few hours, and I can switch out the `forEach` statements with something simpler, and send in a new push request.

**Comment by Joseph-Alley** [comment]
Okay, I've created a push request to fix this, here: https://github.com/innoveit/react-native-ble-manager/pull/970

**Pull request merged**
