### PR TITLE
fix 16 bit uuid and stopScan error

### PR DESCRIPTION
**Pull request by kevyu**
This PR fix two issues I encountered in development:
1. error occurs when the service uuid and characteristic uuid is 16 bit
2. stopScan does not work in android version >= 5.0

### CODE REVIEW

**Comment by vinayr** [comment]
+1 
I am now switching between `XXXX` for iOS and `0000XXXX-0000-1000-8000-00805F9B34FB` for Android

**Comment by marcosinigaglia** [comment]
Hi, this PR breaks the API 18 compatibility, I can't merge.

**Comment by kevyu** [comment]
@marcosinigaglia Could you point out which part break the compatibility?  I am not good at android development, but I test the code at android 4.4 device and i works well.

**Comment by marcosinigaglia** [comment]
I'm not an expert on Android but I think @TargetApi(Build.VERSION_CODES.LOLLIPOP) restrict the code to API 21

**Comment by joshuar500** [comment]
+1 this is the fix needed for Android error: 'Invalid UUID: 1234'

**Comment by marcosinigaglia** [comment]
Hi, I fix the uuid problem in 2.4.0, @kevyu I need to test if TargetApi create problems.

**Comment by marcosinigaglia** [comment]
@kevyu I figure out the problem and i rewrite your fix with the scan style, thanks for the PR

**Pull request closed without merging**
