### PR TITLE
Change a decoder and an encoder

### PR DESCRIPTION
**Pull request by wzh19960613**
- Change the `value` of `BleManagerDidUpdateValueForCharacteristic` from
hex to base64 encoded
- Change the `data` of `write` from base64 encoded to un-encoded string,
byte-array or buffer

### CODE REVIEW

**Comment by marcosinigaglia** [comment]
Hi, what is the purpose?

**Comment by wzh19960613** [comment]
@marcosinigaglia Hi.
The first step is bcz it will **be faster and more convenient** when we get the `value` and translate it from `string` to `bytes`. In general we **need the `bytes` rather than `hex`**.
The second step is bcz we can use raw bytes or a raw string to call the `write` func **without requiring users to encode them**. So we don't need require a `base64` in the doc or dependency, and it 's faster than `base64` too ^-^

**Comment by marcosinigaglia** [comment]
Does not need any code changes on iOS?

**Comment by wzh19960613** [comment]
Eh... Sorry for that, I forgot this. I 'm using RN in an android project only so I didn't consider about the code in iOS.

**Comment by Cretezy** [comment]
I agree with the idea of having a way to send/receive `bytes`, and simply have a base64 decoder on top of the bytes code.

**Pull request closed without merging**
