### PR TITLE
Add turbo modules support

### PR DESCRIPTION
**Pull request by lucaswitch**
This PR is still on development process so things can be broken.

Things are being done using the official docs and keeping backwards compat in mind.
New arch support can be tested using the examplenewarch app and old arch using the default example app.
Reference: https://github.com/reactwg/react-native-new-architecture/blob/main/docs/appendix.md

### CODE REVIEW

**Comment by lucaswitch** [comment]
> Hi, I migrated the Android side but the swift side is not so simple. The documentation and the examples are not correct (https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/swift-event-emitter) so I have to find out other examples.

I guess we can still use the same RctEventEmitter or am i wrong about that?
Because most of libraries that i looked into was still using the old "sendEvent" and still works on 0.76.

**Comment by lucaswitch** [comment]
> > Hi, I migrated the Android side but the swift side is not so simple. The documentation and the examples are not correct (https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/swift-event-emitter) so I have to find out other examples.
> 
> I guess we can still use the same RctEventEmitter or am i wrong about that? Because most of libraries that i looked into was still using the old "sendEvent" and still works on 0.76.

Actually i'm wrong about that, look: https://github.com/react-native-community/RNNewArchitectureLibraries/issues/19#issuecomment-2474160931

**Comment by lucaswitch** [comment]
Screenshot 2024-11-13 at 16 05 10
I'm still trying to figure it out how to solve that for RCT_EXTERN_MODULE macro. @marcosinigaglia can you help with that?

Also i guess we will probably have to add typesafety in all events to be able to send events to codegen.

**Comment by lucaswitch** [comment]
# Events  supported:

They're:
- BleManagerStopScan ❌
- BleManagerDidUpdateState ❌
- BleManagerDiscoverPeripheral ❌
- BleManagerDidUpdateValueForCharacteristic ❌
- BleManagerConnectPeripheral ❌
- BleManagerDisconnectPeripheral ❌
- BleManagerPeripheralDidBond ❌
- BleManagerCentralManagerWillRestoreState (iOS only) ❌
- BleManagerDidUpdateNotificationStateFor (iOS only) ❌
- BleManagerCompanionPeripheral(Android only) ❌
- BleManagerCompanionFailure(Android only)❌

**Comment by marcosinigaglia** [comment]
The Android side with the new event API is working now. The iOS code is crashing so probably the old way to connect the swift code is not working, I'm trying to solve this issue.

**Comment by marcosinigaglia** [comment]
I think now is working, the new structure doesn't make me crazy but the only way I found is to keep a reference between objects in object-c and swift. Implementing the new classes in swift was not enough because the methods that handle events were giving error, if they change in the future you can go back to a structure only in swift. @lucaswitch if you can try to do some testing too. I will remove the new example folder shortly because with expo you can test the new architecture simply without having to have a specific example. For now we don't have time to support the old architecture as well so it will be a breaking change.

**Comment by marcosinigaglia** [comment]
Hi @Marvedog , it would be great if you could do some testing as well. The only breaking changes are in event handling, I have already updated the doc in this PR. I have published version 12.0.0-rc.0 if you need it.

**Comment by lucaswitch** [comment]
> I think now is working, the new structure doesn't make me crazy but the only way I found is to keep a reference between objects in object-c and swift. Implementing the new classes in swift was not enough because the methods that handle events were giving error, if they change in the future you can go back to a structure only in swift. @lucaswitch if you can try to do some testing too. I will remove the new example folder shortly because with expo you can test the new architecture simply without having to have a specific example. For now we don't have time to support the old architecture as well so it will be a breaking change.

Ok, i'll check on the devices that i have here.

**Comment by marcosinigaglia** [comment]
I've tested with a real app ios/android and after few fixes it (12.0.0-rc.2) it seems working. I am waiting for a few more tests to merge.

**Comment by GabrieleMazzola** [comment]
Hey, I'm just going to write here things as I test, hoping it helps.

iOS 18
iPhone 14 Pro

I tried to use the lib in my app with the new architecture, and the app was crashing when calling the `BleManager.start `method, without showing any useful info in the logs.
I then tried to run the iOS app with xcode, and I got the following:
image

Since I am using expo 52 (with `prebuild`), I've now added this to my `app.json`:
```
"infoPlist": {
  "NSBluetoothAlwaysUsageDescription": "This app requires access ..."
}
```
After launching `prebuild` and re-building the app, now I can scan successfully.

Will post more updates as I test, but perhaps this error can be better notified when running the app not natively with xcode.

**Comment by lucaswitch** [comment]
> Hey, I'm just going to write here things as I test, hoping it helps.
> 
> iOS 18 iPhone 14 Pro
> 
> I tried to use the lib in my app with the new architecture, and the app was crashing when calling the `BleManager.start `method, without showing any useful info in the logs. I then tried to run the iOS app with xcode, and I got the following: image
> 
> Since I am using expo 52 (with `prebuild`), I've now added this to my `app.json`:
> 
> ```
> "infoPlist": {
>   "NSBluetoothAlwaysUsageDescription": "This app requires access ..."
> }
> ```
> 
> After launching `prebuild` and re-building the app, now I can scan successfully.
> 
> Will post more updates as I test, but perhaps this error can be better notified when running the app not natively with xcode.

Thats ok, every app that uses bluetooth needs that description and more.
 But it needs to be set on every app as the usage can vary from user to user.

**Comment by marcosinigaglia** [comment]
> > Hey, I'm just going to write here things as I test, hoping it helps.
> > iOS 18 iPhone 14 Pro
> > I tried to use the lib in my app with the new architecture, and the app was crashing when calling the `BleManager.start `method, without showing any useful info in the logs. I then tried to run the iOS app with xcode, and I got the following: image
> > Since I am using expo 52 (with `prebuild`), I've now added this to my `app.json`:
> > ```
> > "infoPlist": {
> >   "NSBluetoothAlwaysUsageDescription": "This app requires access ..."
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After launching `prebuild` and re-building the app, now I can scan successfully.
> > Will post more updates as I test, but perhaps this error can be better notified when running the app not natively with xcode.
> 
> Thats ok, every app that uses bluetooth needs that description and more. But it needs to be set on every app as the usage can vary from user to user.

I added a check to prevent the app from crashing.

**Comment by marcosinigaglia** [comment]
> I got an error in Xcode with version `12.0.0-rc.2`. It is caused from a wrong filename of the Swift->Objective-C bridge header. I opened the PR in the source repo of this PR:
> 
> [lucaswitch#1](https://github.com/lucaswitch/react-native-ble-manager/pull/1)

Your fix is working only if you use `use_frameworks!`, I will check how to fix it and commit to solve the problem.

**Comment by Krupskis** [comment]
Excited to test this as well!

**Comment by matt-42** [comment]
Hi! Thanks a lot for the work. I did a try and I had this error when testing rc3 and using  `bleManagerEmitter.addListener("BleManagerDidUpdateState", ...)`

did the API to listen to ble events has changed ?

```java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x15000010 (has extras) } in it.innove.BleManager$2@6d4f3aa

 android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1852)
  android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
  android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
  android.os.Handler.handleCallback(Handler.java:958)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:224)
  android.os.Looper.loop(Looper.java:318)
  android.app.ActivityThread.main(ActivityThread.java:8777)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by java.lang.RuntimeException: __next_prime overflow
  com.facebook.react.bridge.CxxCallbackImpl.nativeInvoke(Native Method)
  com.facebook.react.bridge.CxxCallbackImpl.invoke(CxxCallbackImpl.java:27)
  it.innove.NativeBleManagerSpec.emitOnDidUpdateState(NativeBleManagerSpec.java:46)
  it.innove.BleManager$MyBroadcastReceiver.onReceive(BleManager.java:142)
  android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1842)
  android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
  android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
  android.os.Handler.handleCallback(Handler.java:958)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:224)
  android.os.Looper.loop(Looper.java:318)
  android.app.ActivityThread.main(ActivityThread.java:8777)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by thehale** [comment]
Jumping in to report that `12.0.0-rc.3` is **working great** in my [`speedcuber-timer`](https://github.com/SpeedcuberOSS/speedcuber-timer) app on RN 0.76 (scanning, connecting, notifications, disconnecting). Thanks so much for the hard work on this!

---

> did the API to listen to ble events has changed ?

@matt-42, yes it did -- see https://github.com/innoveit/react-native-ble-manager/pull/1285/files#diff-0a0e6737f721e95ba0e323dbf727fa099aa28bf25c147fd3fdd7ea36f8dc7e0a.

Previously I had to instantiate a `NativeEventEmitter` and listen to specific documented events.

```typescript
// Before ( <= v11.5.7)
import { NativeEventEmitter, NativeModules } from 'react-native';
import BleManager from 'react-native-ble-manager';

const BleManagerModule = NativeModules.BleManager || {};
const BleEvents = new NativeEventEmitter(BleManagerModule);

 const subscription = BleEvents.addListener(
    'BleManagerDiscoverPeripheral',
    (device) => { /* do stuff */ },
);
```

Now, there are easy-to-use methods directly available on the `BleManager`

```typescript
// After ( >= v12.0.0)
import BleManager from 'react-native-ble-manager';

const subscription = BleManager.onDiscoverPeripheral(
  (device) => { /* do stuff */ }
);
```

**Pull request merged**
